const paragraphs = [
    "Will you only be here for the higher days? When the sweet times are over are you gonna stay? Had to ask you early girl I know I'm late. But if you tell me something then I'll be okay. It's nice to have you but I can't continue, With these thoughts in my head. You can bring me back to life with just a word. I need those fake assurances, e dey keep me very sane. I be up 'til the sunset (be up) Before the sunrise I'm already out here I don't spend too much time with the bed. No one told that me time was bread, I figured it myself And I'm trynna make life easy for us (easy for, easy) Watch your back and give you that, D D when you want it. I'm not here to let you please me, oh nah Say a word it might complete me o It might complete me o I live deep down in your toxic love city...",

"The emperor e no get no clothes on. Bought himself a cloud nine, that's what he floats on Ego be ein medicine, gets his daily dose on .Too far gone to know what dey gon on. Fine women fine linen, chale that's a given. The motto be 'forget dem' who are we kidding Stone cold prison sponsored by myopia Slogan of the century must be yentie obiaa. The people no get bread Then for petes sake let them eat cake. My big statue reminds them we are too great. What i for do bout the hullaboloo and the much ado. Biggest palanquin you ever seen, i am breaking news. Have you ever seen a king, Who was not a man? Have you ever seen a statue Giving out commands?...",

"Plenty boys them give me stories. They go dey ask me why I dey worry. Steady acting like they know me.Big smiles on their faces nanso KK Rasta menhwe obi. I've been down here since early. Oh boy I pay my dues they know me.They try calculate my moves them no fit. Where too be bold I don't care about who no dey rate me. We don't need man's to believe. We don't care about who no dey see What we dey see now bros believe. We're on the winning side they dey see We don't need man's to believe. We don't care about who no dey see. What we dey see now bros believe. We on the winning side they dey see. Simmer down. My thing from Babylon tell me boy Simmer down. I know you're losing your mind But cool e temper. My thing from Babylon tell me boy Simmer down...",

"I just wanna make love And money. Walahi suffer suffer life is not for me. See me I come from nothing. See me I come from trenches Nothing dey my aza for 14 days And nobody feel my pain uh huh. I will never be the same uh huh. I was a different case uh huh When dem look my side dem dey say ah ah. Nobody pass the almighty. Nobody fit follow me fight. My face show my shoe shine. Hallelujah, I'm getting mula Inside cooler, eating suya Hallelujah Living la vida loca. Owo wole.I be on the road all day I'm chasing mula. Fire dey my mouth like azula. Turn a magic beat into suya. I be on the road all day I'm chasing mula. Fire dey my mouth like azula. Turn a magic beat into suya. I been hot for like 4 years, and they wonder if I'm done yet. People be like rice for my concert. Welcome welcome the new converts. In a whip wey dey convert...",

"I done gave my all to you, fell in the deep end. You done came into my life while I was sinking. I been on that type time with demons. All the times I was outside, I was creeping. It was love at first sight, girl, when you walked in. Couldn't look deep in your eyes 'cause I get locked in. You was hurtin' deep inside and you was broken But I was on the other side and didn't notice. Oh-oh-oh, I won't waste no time I won't waste my time when it come to you. Put my pride aside, give it all to you. Put my pride aside, no, oh Girl, I won't waste no time. I won't waste my time when it comes to you. Put my pride aside, give it all to you. Put my pride aside, give it all to...",

"You not a real stepper, you can't overstep me. Just sit back and listen and watch how he bless me. He wait 'til I fall and then pull up and catch me Your check is too small, you can't run up and check me Nah, nah, I get 'em fast, see. You feel a way, then go pull up and get me. Might do something wild if I feel like you press me. Nah, I get 'em fast, see. You feel a way, then go pull up and get me. Might do something wild if I feel like you press me. We off the grid, grid, grid. This for my kid, kid, kid. For when my kid-kid-kids have kids. Everything we did for the crib. Pray for what folks them did. Only thing we pray God forgive-give-give. May God forbid-bid-bid. He hit one of the kids, kids, kids. Took off his list, list, list. Look what they did, did, did Pray for the crib, crib, crib. Some say A-a-adam could never be bla-a-ack. 'Cause a black man'll never share his rib, rib, rib, rib, rib, rib",

"God in my cell, that's my celly. Made in the image of God, that's a selfie. Pray five times a day, so many felonies. Who gon' post my bail? Lord, help me Hol' up, Donda, I'm with your baby when I touch back roadTold him,Stop all of that red cap, we goin' home..."
]